project:
  type: website
  output-dir: docs

website:
  title: "BST623 functions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Glossary.qmd

format:
  html:
    theme: 
      - cosmo
      - assets/style.scss
    toc: true

editor: source

