project:
  type: website
  output-dir: docs

website:
  title: "BST623 functions"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Glosary.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

