# [`distinct()`]{.blue} 
 
 
### 
{.center} 
 
# What it does 

+ [`distinct()`]{.blue} shows unique values.
  
 
# Demo code 


.blue[`distinct`]`(table, variables)`
```{r, eval = FALSE}
laryngectomy|> distinct(gender)
laryngectomy |> distinct(int_stg)
laryngectomy |> 
  mutate(isMale = 2 - gender ) |> 
  mutate(sex = as.character(isMale)) |> 
  mutate(sex = fct_recode(sex,
                          "Female" = "0",
                          "Male" = "1")) |> 
  mutate(stage = fct_recode(as.character(int_stg),
                          "T1" = "1",
                          "T2" = "2",
                          "T3" = "3",
                          "T4" = "4",
                          "Unknown" = "5")) |> 
  `distinct(sex, stage)` |> 
  arrange(sex, stage)
```
]
.ver
```{r include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
laryngectomy <- lr4ds::laryngectomy
```
```{r, echo = FALSE}
laryngectomy |> distinct(gender)
laryngectomy |> distinct(int_stg)
laryngectomy |> 
  mutate(isMale = 2 - gender ) |> 
  mutate(sex = as.character(isMale)) |> 
  mutate(sex = fct_recode(sex,
                          "Female" = "0",
                          "Male" = "1"))  |> 
  mutate(stage = fct_recode(as.character(int_stg),
                          "T1" = "1",
                          "T2" = "2",
                          "T3" = "3",
                          "T4" = "4",
                          "Unknown" = "5")) |> 
  distinct(sex, stage) |> 
  arrange(sex, stage)
```
]]
  
 
# Usefull stuff 

.related-functions[]
  
 
# Common Problems 

  
 
# Related Functions 
NA  
