# Function name: if_else()
# Notes:
# [`dplyr::if_else()`]
[[`if_else`]`(*check*, *true*, *false*)`]
+ `if_else()` checks the truth of a logic *check* on a variable/vector and returns the *true* argument if it is true or the *false* argument if it is not true.
```{r eval=FALSE}
laryngectomy %>%
  mutate(  # does the initial stage agree with final pathology staging?
    path_result = if_else(int_stg != path_stg, "Changed", "Same")
  ) %>%
  select(int_stg, path_stg, path_result)
```
+ The logic check can involve any number of variables.
+ [`if_else()`] is dangerous because unexpected values can be binned in the *false* level/group.
---


# Introduction to If_Else Function
If_Else is a language construct for programming in R. It is used for decision making processes and for executing a different code block depending on whether a condition is true or not.

## What Package Contains It
The If_Else function is part of the base R package and is included when users download the R program to their computers.

## When To Use It
If_Else is used to create an 'if-else' logic condition. This is used to execute one code block when a condition is TRUE and a different code