# Function name: typeof()
# Notes:
# [`typeof()`]
.small[
[[`typeof`]`(*vector*)`]
[[`typeof`]`(*dataset$variable*)`]
+ The "type" of an object helps determine what behaviors an object can do.  
  + You can not take the mean of a character variable.
+ These are the typical types that are used in datasets:
.pull-left[
+ int = "integer" for numbers without decimals
+ dbl = "double" for numbers with decimals 
+ lgl = "logical" for true/false
+ date = "date"]
.pull-right[
+ chr = "character" for character string
+ fct = "factor" for categories that are not ordered
+ ord = "ordered" for ordered categories
]  
```{r eval=FALSE}
typeof(pi)
typeof(R.version$nickname)
```
+ Other "types" are used to categorize functions and other complex objects.
+ `R` also uses [`mode()`] to describe type.  It groups "integer" and "double" as "numeric".
]
---


# typeof function 

The typeof function is a basic R function that determines the type of object passed to it. 

The typeof function belongs to the base package of R.

The typeof function should be used when you need to determine the class of an object. This is important to know because each class of object has specific methods and functions that can be used on them.

An example of how to use the typeof function in R is as follows:

```R
# Determine the type of the object 'x'